physics:
  dt: 0.002                # 500Hz
  mpc_frequency: 80       
  scene: "flat"            # flat, random_boxes, perlin
  gravity: 9.81
  mu: 0.5
  
verbose: true

optimize:
  use_feedback_linearization: true
  use_foothold_optimization: false

  use_foothold_constraint: true
  use_static_stability: false
  use_zmp_stability: false

  use_warm_start: true

ik_solver:
  use_ik: false
  ik_iterations: 20
  ik_dt: 0.01
  ik_damping: 0.001
  max_pos_diff: 2
  max_vel_diff: 5

render:
  render_frequency: 30
  show_velocity_vector: true
  show_swing_trajectory: false  
  show_footholds: false

gait:
  active: "trot"  # options: trot, pace, crawl, full_stance

  gaits:
    trot:
      duty_factor: 0.6
      step_freq: 1.4
      margin: 0.04
      phase_offsets: [0.5, 1.0, 1.0, 0.5] # FL, FR, RL, RR
    
    pace:
      duty_factor: 0.7
      step_freq: 1.4
      margin: 0.1
      phase_offsets: [0.8, 0.3, 0.8, 0.3]
    
    # bounding:
    #   type: 4 
    #   duty_factor: 0.65
    #   step_freq: 1.8
    #   phase_offsets: [0.5, 0.5, 0.0, 0.0]

    crawl:
      duty_factor: 0.8
      step_freq: 0.5
      margin: 0.02
      phase_offsets: [0.0, 0.5, 0.75, 0.25]

    full_stance: 
      duty_factor: 0.6
      step_freq: 2.0
      phase_offsets: [0.0, 0.0, 0.0, 0.0]
